export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const START_EDIT_SERVICE = 'START_EDIT_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const FILTER = 'FILTER';